### ISSUE TITLE
Issues with the menu close function

### ISSUE THREAD

**Issue by DaJazz246-2** [SeaPuppy2006/FruitClicker#6]
I don't like how you need to click the X to close the menus in this game as it basically cripples new players.
I would prefer to there be a close button inside the window.

also make the fullscreen scale already please and thank you.

**Comment by SeaPuppy2006** [comment]
space restricts this but i will try to complement this function. fullscreen is under developmemnt

**Comment by SeaPuppy2006** [comment]
Main issue done. Fullscreen still under dev
