### ISSUE TITLE
Visual glitch for the munch

### ISSUE THREAD

**Issue by DaJazz246-2** [SeaPuppy2006/FruitClicker#7]
![image](https://user-images.githubusercontent.com/67458659/85836050-5d572580-b7d9-11ea-97c2-71d31ed7871c.png)
After I convert all munch ( notice it moves to the right also, maybe related?)
![image](https://user-images.githubusercontent.com/67458659/85836093-6f38c880-b7d9-11ea-92cc-6014d9015777.png)
Before I converted the munch
this was after i got LV 2 munch convert
valve pls fix

**Comment by SeaPuppy2006** [comment]
DaJazz246-2 Can you please be more specific, i cant figure out exactly what your problem is with the game. Thanks.

**Comment by SeaPuppy2006** [comment]
Fixed until further notice with recent commits.
